#pragma once
#include "swConfigTypes.h"
#include "swConfig.h"
#include "stdint.h"
#include "gpio.h"
#include "adc.h"

/* Private defines generated by STM Cube in main.h file -----------------------*/

#define Button_1_Pin GPIO_PIN_8
#define Button_1_GPIO_Port GPIOA
#define Button_2_Pin GPIO_PIN_8
#define Button_2_GPIO_Port GPIOC
#define Button_3_Pin GPIO_PIN_9
#define Button_3_GPIO_Port GPIOA
#define Button_4_Pin GPIO_PIN_7
#define Button_4_GPIO_Port GPIOC
#define Button_5_Pin GPIO_PIN_13
#define Button_5_GPIO_Port GPIOC
#define Button_6_Pin GPIO_PIN_3
#define Button_6_GPIO_Port GPIOA
#define Potentiometer_1_Pin GPIO_PIN_1
#define Potentiometer_1_GPIO_Port GPIOB

/* ---------------------------------------------------------------------------*/


/* Variables -----------------------------------------------------------------*/

//ADC_HandleTypeDef hadc1;

/* ---------------------------------------------------------------------------*/


/* Function prototypes--------------------------------------------------------*/

SwVoltageType SW_GetAnalogInputValue();
SwButtonStatusType SW_GetDigitalInputValue(SwInputIndexType inputIndex);
void Sw_InitializeInputs();

/* ---------------------------------------------------------------------------*/
